package vista_departamentos;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import selector_vista.EventoVista;
import vista.Vista;
import controlador.ControladorAplicacionImp;
import controlador.EventoNegocio;
import departamento.Departamento;
import empleado.Empleado;

/**
*
* @author Daniel
*/
public class MostrarDepartamento extends javax.swing.JFrame implements Vista {
	
	static private MostrarDepartamento mostrarDepartamento;
	
	private MostrarDepartamento(){
		initComponents();
	}

	static public MostrarDepartamento obtenerInstancia(){
		if(mostrarDepartamento == null){
			mostrarDepartamento = new MostrarDepartamento();
		}
		
		return mostrarDepartamento;
	}
	
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
	   
	   this.setTitle("Mostrar Departamento");

       jLabel1 = new javax.swing.JLabel();
       jFormattedTextField1 = new javax.swing.JFormattedTextField();
       jLabel2 = new javax.swing.JLabel();
       jFormattedTextField2 = new javax.swing.JFormattedTextField();
       jLabel3 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTextArea1 = new javax.swing.JTextArea();
       jLabel4 = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jLabel1.setText("ID");

       jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jFormattedTextField1ActionPerformed(evt);
           }
       });

       jLabel2.setText("Nombre");

       jFormattedTextField2.setEditable(false);

       jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
       jLabel3.setText("Empleados");

       jTextArea1.setColumns(20);
       jTextArea1.setRows(5);
       jScrollPane1.setViewportView(jTextArea1);

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel1)
                           .addComponent(jLabel2))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jFormattedTextField2, 0, 0, Short.MAX_VALUE)
                           .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                   .addComponent(jLabel4)
                   .addComponent(jLabel3))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel2)
                   .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel4)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
               .addContainerGap())
       );
       
       addWindowListener(new java.awt.event.WindowAdapter() { //cuando se cirre la pestaña borra lo anterior
           public void windowClosing(java.awt.event.WindowEvent evt) {
       		jFormattedTextField1.setText("");
    		jFormattedTextField2.setText("");
    		jTextArea1.setText(""); //borra lo anterior
           }
       });

		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
       
       pack();
   }// </editor-fold>

   private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
       ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.MOSTAR_DEPARTAMENTO, Integer.valueOf(jFormattedTextField1.getText()).intValue());
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new MostrarDepartamento().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JFormattedTextField jFormattedTextField1;
   private javax.swing.JFormattedTextField jFormattedTextField2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration

	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		jFormattedTextField1.setText("");
		jFormattedTextField2.setText("");
		jTextArea1.setText(""); //borra lo anterior
		
		if(id_evento_vista == EventoVista.MOSTAR_DEPARTAMENTO_EXITO){
			Departamento departamento = (Departamento)datos;
			
			jFormattedTextField2.setText(departamento.getNombre());
			
			jTextArea1.append("ID\tDNI\tNOMBRE APELLIDOS\n\n");
			
			for(Empleado e: departamento.getLista_empleados()){
				jTextArea1.append(e.getId()+"\t"+e.getDni().toString() + "\t" + e.getNombre_apellidos() + "\n"); 
			}
		}
		else if(id_evento_vista == EventoVista.MOSTAR_DEPARTAMENTO_FALLO){
			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el departamento que se desea mostrar", "Baja Departamento", JOptionPane.ERROR_MESSAGE);
		}
		
	}

}
