package vista_departamentos;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import selector_vista.EventoVista;
import vista.Vista;
import controlador.ControladorAplicacionImp;
import controlador.EventoNegocio;
import departamento.Departamento;

/**
*
* @author Daniel
*/
public class NuevoDepartamento extends javax.swing.JFrame implements Vista {
	
	static private NuevoDepartamento nuevoDepartamento;

   /** Creates new form NuevoDepartamento */
   private NuevoDepartamento() {
       initComponents();
   }
   
   /**
    * Obtiene la instancia de la ventana
    * @return la instancia de la ventana
    */
   static public NuevoDepartamento obtenerInstancia(){
	   if(nuevoDepartamento == null){
		   nuevoDepartamento = new NuevoDepartamento();
	   }
	   
	   return nuevoDepartamento;
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
	   
	   this.setTitle("Nuevo Departamento");

       jLabel1 = new javax.swing.JLabel();
       jFormattedTextField1 = new javax.swing.JFormattedTextField();
       jButton1 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jLabel1.setText("Nombre Departamento");

       jButton1.setText("Aceptar");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jButton1)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addGap(49, 49, 49)
                       .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addComponent(jButton1)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
       
       pack();
   }// </editor-fold>

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	   Departamento departamento = new Departamento(jFormattedTextField1.getText());
	   departamento.setActivo(true);
       ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.NUEVO_DEPARTAMENTO, departamento);
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new NuevoDepartamento().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton jButton1;
   private javax.swing.JFormattedTextField jFormattedTextField1;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration
   
	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		if(id_evento_vista == EventoVista.NUEVO_DEPARTAMENTO_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha creado el departamento con éxito con id " + (int)datos, "Creación Departamento", JOptionPane.INFORMATION_MESSAGE);
			
		}	
		else if(id_evento_vista == EventoVista.NUEVO_DEPARTAMENTO_NOMBRE_EXISTE){
			JOptionPane.showMessageDialog(null, "ERROR!! Ya existe un departamento con ese nombre", "Creación Departamento", JOptionPane.ERROR_MESSAGE);
		}
		else{
			JOptionPane.showMessageDialog(null, "ERROR!! El departamento no se ha creado", "Creación Departamento", JOptionPane.ERROR_MESSAGE);
		}
	}

}
