package vista;

import java.awt.BorderLayout;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import vista_departamentos.BajaDepartamento;
import vista_departamentos.MostrarDepartamento;
import vista_departamentos.MostrarDepartamentos;
import vista_departamentos.NuevoDepartamento;
import vista_empleados.AsignarTarea;
import vista_empleados.BajaEmpleado;
import vista_empleados.MostrarEmpleado;
import vista_empleados.MostrarEmpleados;
import vista_empleados.NuevoEmpleado;
import vista_facturas.AsignarFactura;
import vista_facturas.BorrarFactura;
import vista_facturas.ModificarFactura;
import vista_facturas.MostrarFactura;
import vista_facturas.MostrarFacturas;
import vista_facturas.NuevaFactura;
import vista_habitaciones.BorrarHabitacion;
import vista_habitaciones.ModificarHabitacion;
import vista_habitaciones.MostrarHabitacion;
import vista_habitaciones.MostrarHabitaciones;
import vista_habitaciones.NuevaHabitacion;
import vista_residentes.BorrarResidente;
import vista_residentes.ModificarResidente;
import vista_residentes.MostrarResidente;
import vista_residentes.MostrarResidentes;
import vista_residentes.MostrarResidentesSuperanFacturas;
import vista_residentes.NuevoResidente;
import vista_tareas.BajaTarea;
import vista_tareas.MostrarTarea;
import vista_tareas.MostrarTareas;
import vista_tareas.NuevaTarea;

/**
 * 
 * @author Daniel 2.0
 */
public class MainFrame extends javax.swing.JFrame {

	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		pestanaResidente = new javax.swing.JMenu();
		botonNuevoResidente = new javax.swing.JMenuItem();
		botonBorrarResidente = new javax.swing.JMenuItem();
		botonModifcarResidente = new javax.swing.JMenuItem();
		botonMostrarResidente = new javax.swing.JMenuItem();
		botonMostrarResidentes = new javax.swing.JMenuItem();
		pestanaHabitacion = new javax.swing.JMenu();
		botonNuevaHabitacion = new javax.swing.JMenuItem();
		botonBorrarHabitacion = new javax.swing.JMenuItem();
		botonModificarHabitacion = new javax.swing.JMenuItem();
		botonMostrarHabitacion = new javax.swing.JMenuItem();
		botonMostrarHabitaciones = new javax.swing.JMenuItem();
		pestanaFactura = new javax.swing.JMenu();
		botonNuevaFactura = new javax.swing.JMenuItem();
		botonBorrarFactura = new javax.swing.JMenuItem();
		botonModificarFactura = new javax.swing.JMenuItem();
		botonMostrarFactura = new javax.swing.JMenuItem();
		botonMostrarFacturas = new javax.swing.JMenuItem();
		botonAsignarFactura = new javax.swing.JMenuItem();
		pestanaEmpleado = new javax.swing.JMenu();
		botonNuevoEmpleado = new javax.swing.JMenuItem();
		botonBajaEmpleado = new javax.swing.JMenuItem();
		botonMostrarEmpleado = new javax.swing.JMenuItem();
		botonMostrarEmpleados = new javax.swing.JMenuItem();
		botonAsignarTarea = new javax.swing.JMenuItem();
		pestanaDepartamento = new javax.swing.JMenu();
		botonNuevoDepartamento = new javax.swing.JMenuItem();
		botonBajaDepartamento = new javax.swing.JMenuItem();
		botonMostrarDepartamento = new javax.swing.JMenuItem();
		botonMostrarDepartamentos = new javax.swing.JMenuItem();
		pestanaTarea = new javax.swing.JMenu();
		botonNuevaTarea = new javax.swing.JMenuItem();
		botonBajaTarea = new javax.swing.JMenuItem();
		botonMostrarTarea = new javax.swing.JMenuItem();
		botonMostrarTareas = new javax.swing.JMenuItem();
		
		botonMostrarResidentesFacturasSuperadas = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		// setIconImage(Constants.icono);
		setResizable(false);
		
		/*
		Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono.png"));
		setIconImage(icono);
		*/
		
		this.setTitle("Residentator 2.0");
		
		pestanaResidente.setText("Residente");
;
		botonNuevoResidente.setText("Nuevo Residente");
		botonNuevoResidente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevoResidenteActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonNuevoResidente);
;
		botonBorrarResidente.setText("Borrar Residente");
		botonBorrarResidente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarResidenteActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonBorrarResidente);

		botonModifcarResidente.setText("Modifcar Residente");
		botonModifcarResidente.setActionCommand("Modificar Residente");
		botonModifcarResidente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarResidenteActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonModifcarResidente);

		botonMostrarResidente.setText("Mostrar Residente");
		botonMostrarResidente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarResidenteActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonMostrarResidente);

		botonMostrarResidentes.setText("Mostrar Residentes");
		botonMostrarResidentes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarResidentesActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonMostrarResidentes);
		
		botonMostrarResidentesFacturasSuperadas.setText("Mostrar Residentes Superan Facturas");
		botonMostrarResidentesFacturasSuperadas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarResidentesFacturasSuperadasActionPerformed(evt);
			}
		});
		pestanaResidente.add(botonMostrarResidentesFacturasSuperadas);

		jMenuBar1.add(pestanaResidente);

		pestanaHabitacion.setText("Habitacion");

		botonNuevaHabitacion.setText("Nueva Habitacion");
		botonNuevaHabitacion.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevaHabitacionActionPerformed(evt);
					}
				});
		pestanaHabitacion.add(botonNuevaHabitacion);

		botonBorrarHabitacion.setText("Borrar Habitacion");
		pestanaHabitacion.add(botonBorrarHabitacion);
		botonBorrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarHabitacionActionPerformed(evt);
			}
		});

		botonModificarHabitacion.setText("Modificar Habitacion");
		pestanaHabitacion.add(botonModificarHabitacion);
		botonModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarHabitacionActionPerformed(evt);
			}
		});

		botonMostrarHabitacion.setText("Mostrar Habitacion");
		pestanaHabitacion.add(botonMostrarHabitacion);
		botonMostrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarHabitacionActionPerformed(evt);
			}
		});

		botonMostrarHabitaciones.setText("Mostrar Habitaciones");
		pestanaHabitacion.add(botonMostrarHabitaciones);
		botonMostrarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarHabitacionesActionPerformed(evt);
			}
		});

		jMenuBar1.add(pestanaHabitacion);

		pestanaFactura.setText("Factura");

		botonNuevaFactura.setText("Nueva Factura");
		botonNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevaFacturaActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonNuevaFactura);

		botonBorrarFactura.setText("Borrar Factura");
		botonBorrarFactura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBorrarFacturaActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonBorrarFactura);

		botonModificarFactura.setText("Modificar Factura");
		botonModificarFactura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonModificarFacturaActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonModificarFactura);

		botonMostrarFactura.setText("Mostrar Factura");
		botonMostrarFactura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarFacturaActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonMostrarFactura);

		botonMostrarFacturas.setText("Mostrar Facturas");
		botonMostrarFacturas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarFacturasActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonMostrarFacturas);
		
		botonAsignarFactura.setText("Asignar Factura");
		botonAsignarFactura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAsignarFacturaActionPerformed(evt);
			}
		});
		pestanaFactura.add(botonAsignarFactura);

		jMenuBar1.add(pestanaFactura);

		pestanaEmpleado.setText("Empleado");

		botonNuevoEmpleado.setText("Nuevo empleado");
		botonNuevoEmpleado
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevoEmpleadoActionPerformed(evt);
					}
				});
		pestanaEmpleado.add(botonNuevoEmpleado);

		botonBajaEmpleado.setText("Baja empleado");
		botonBajaEmpleado
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonBajaEmpleadoActionPerformed(evt);
					}
				});
		pestanaEmpleado.add(botonBajaEmpleado);
		

		botonMostrarEmpleado.setText("Mostrar empleado");
		botonMostrarEmpleado
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarEmpleadoActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonMostrarEmpleado);

		botonMostrarEmpleados.setText("Mostrar empleados");
		
		
		botonMostrarEmpleados
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarEmpleadosActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonMostrarEmpleados);
	

		botonAsignarTarea.setText("Asignar tarea");
		botonAsignarTarea
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonAsignarTareaActionPerformed(evt);
			}
		});
		pestanaEmpleado.add(botonAsignarTarea);

		jMenuBar1.add(pestanaEmpleado);

		pestanaDepartamento.setText("Departamento");

		botonNuevoDepartamento.setText("Nuevo departamento");
		botonNuevoDepartamento
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonNuevoDepartamentoActionPerformed(evt);
					}
				});
		pestanaDepartamento.add(botonNuevoDepartamento);

		botonBajaDepartamento.setText("Baja departamento");
		botonBajaDepartamento
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						botonBajaDepartamentoActionPerformed(evt);
					}
				});
		pestanaDepartamento.add(botonBajaDepartamento);

		botonMostrarDepartamento.setText("Mostrar departamento");
		botonMostrarDepartamento
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarDepartamentoActionPerformed(evt);
			}
		});
		pestanaDepartamento.add(botonMostrarDepartamento);

		botonMostrarDepartamentos.setText("Mostrar departamentos");
		botonMostrarDepartamentos
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarDepartamentosActionPerformed(evt);
			}
		});
		pestanaDepartamento.add(botonMostrarDepartamentos);

		jMenuBar1.add(pestanaDepartamento);

		pestanaTarea.setText("Tarea");

		botonNuevaTarea.setText("Nueva tarea");
		botonNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonNuevaTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonNuevaTarea);

		botonBajaTarea.setText("Baja tarea");
		botonBajaTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonBajaTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonBajaTarea);

		botonMostrarTarea.setText("Mostrar tarea");
		botonMostrarTarea.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarTareaActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonMostrarTarea);

		botonMostrarTareas.setText("Mostrar tareas");
		botonMostrarTareas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonMostrarTareasActionPerformed(evt);
			}
		});
		pestanaTarea.add(botonMostrarTareas);

		jMenuBar1.add(pestanaTarea);

		setJMenuBar(jMenuBar1);

		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
		
		JLabel label = new JLabel("", image, JLabel.CENTER);
		
		JPanel panel = new JPanel(new BorderLayout());
		
		panel.add( label, BorderLayout.CENTER );
		
		this.add(panel);
		
		JLabel descripcion = new JLabel("Un sistema capaza de gestionar una residencia de estudiantes.");
		
		
		descripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); 
		
		panel.add( descripcion, BorderLayout.SOUTH );
		
		pack();
	}// </editor-fold>

	//ACCIONES HABITACIONES
	private void botonNuevaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		NuevaHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarHabitacion.obtenerInstancia().setVisible(true);
	
	}
	
	private void botonModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarHabitacion.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarHabitaciones.obtenerInstancia().mostrar();
		MostrarHabitaciones.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES RESIDENTES
	private void botonNuevoResidenteActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoResidente.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarResidenteActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarResidente.obtenerInstancia().setVisible(true);
	}
	
	private void botonModificarResidenteActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarResidente.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarResidenteActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarResidente.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarResidentesActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarResidentes.obtenerInstancia().mostrar();
		MostrarResidentes.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarResidentesFacturasSuperadasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarResidentesSuperanFacturas.obtenerInstancia().mostrar();
		MostrarResidentesSuperanFacturas.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES FACTURAS
	private void botonNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {
		NuevaFactura.obtenerInstancia().setVisible(true);
	}
	
	private void botonBorrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {
		BorrarFactura.obtenerInstancia().setVisible(true);
	}
	
	private void botonModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {
		ModificarFactura.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarFactura.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarFacturasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarFacturas.obtenerInstancia().mostrar();
		MostrarFacturas.obtenerInstancia().setVisible(true);
	}
	
	private void botonAsignarFacturaActionPerformed(java.awt.event.ActionEvent evt) {
		AsignarFactura.obtenerInstancia().setVisible(true);
	}
	
	//ACCIONES EMPLEADOS
	private void botonNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoEmpleado.obtenerInstancia().setVisible(true);
	}
	
	private void botonBajaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		BajaEmpleado.obtenerInstancia().setVisible(true);
	
	}
	private void botonMostrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
		
		MostrarEmpleado.obtenerInstancia().setVisible(true);
		
	}
	private void botonMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {
	
		MostrarEmpleados.obtenerInstancia().mostrar();
		MostrarEmpleados.obtenerInstancia().setVisible(true);
	}
	private void botonAsignarTareaActionPerformed(java.awt.event.ActionEvent evt) {
		
		AsignarTarea.obtenerInstancia().setVisible(true);
	}

	//ACCIONES DEPARTAMENTOS

	private void botonNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
		NuevoDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonBajaDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
			BajaDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarDepartamento.obtenerInstancia().setVisible(true);
	}
	
	private void botonMostrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarDepartamentos.obtenerInstancia().mostrar();
		MostrarDepartamentos.obtenerInstancia().setVisible(true);
	}

	//ACCIONES TAREAS
	private void botonNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {
	  NuevaTarea.obtenerInstancia().setVisible(true);
	}

	private void botonBajaTareaActionPerformed(java.awt.event.ActionEvent evt) {
		BajaTarea.obtenerInstancia().setVisible(true);
	}
	private void botonMostrarTareaActionPerformed(java.awt.event.ActionEvent evt) {
	MostrarTarea.obtenerInstancia().setVisible(true);
	}
	private void botonMostrarTareasActionPerformed(java.awt.event.ActionEvent evt) {
		MostrarTareas.obtenerInstancia().mostrar();
		MostrarTareas.obtenerInstancia().setVisible(true);
	}
	
	
	
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	
	private javax.swing.JMenuItem botonAsignarTarea;
	private javax.swing.JMenuItem botonBajaDepartamento;
	private javax.swing.JMenuItem botonBajaEmpleado;
	private javax.swing.JMenuItem botonBajaTarea;
	private javax.swing.JMenuItem botonBorrarFactura;
	private javax.swing.JMenuItem botonBorrarHabitacion;
	private javax.swing.JMenuItem botonBorrarResidente;
	private javax.swing.JMenuItem botonModifcarResidente;
	private javax.swing.JMenuItem botonModificarFactura;
	private javax.swing.JMenuItem botonModificarHabitacion;
	private javax.swing.JMenuItem botonMostrarDepartamento;
	private javax.swing.JMenuItem botonMostrarDepartamentos;
	private javax.swing.JMenuItem botonMostrarEmpleado;
	private javax.swing.JMenuItem botonMostrarEmpleados;
	private javax.swing.JMenuItem botonMostrarFactura;
	private javax.swing.JMenuItem botonMostrarFacturas;
	private javax.swing.JMenuItem botonMostrarHabitacion;
	private javax.swing.JMenuItem botonMostrarHabitaciones;
	private javax.swing.JMenuItem botonMostrarResidente;
	private javax.swing.JMenuItem botonMostrarResidentes;
	private javax.swing.JMenuItem botonMostrarTarea;
	private javax.swing.JMenuItem botonMostrarTareas;
	private javax.swing.JMenuItem botonNuevaFactura;
	private javax.swing.JMenuItem botonNuevaHabitacion;
	private javax.swing.JMenuItem botonNuevaTarea;
	private javax.swing.JMenuItem botonNuevoDepartamento;
	private javax.swing.JMenuItem botonNuevoEmpleado;
	private javax.swing.JMenuItem botonNuevoResidente;
	private javax.swing.JMenuItem botonAsignarFactura;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenu pestanaDepartamento;
	private javax.swing.JMenu pestanaEmpleado;
	private javax.swing.JMenu pestanaFactura;
	private javax.swing.JMenu pestanaHabitacion;
	private javax.swing.JMenu pestanaResidente;
	private javax.swing.JMenu pestanaTarea;
	// End of variables declaration
	
	private javax.swing.JMenuItem botonMostrarResidentesFacturasSuperadas;

}
