package vista_empleados;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import controlador.ControladorAplicacionImp;
import controlador.EventoNegocio;
import selector_vista.EventoVista;
import vista.Vista;

/**
*
* @author Daniel
*/
public class BajaEmpleado extends javax.swing.JFrame implements Vista{
	
	static private BajaEmpleado bajaEmpleado;

	private BajaEmpleado() {
       initComponents();
	}
   
	/**
	 * Obtiene la instancia de la ventana
	 * @return la instancia de la ventana
	 */
	static public BajaEmpleado obtenerInstancia(){
		if(bajaEmpleado == null){
			bajaEmpleado = new BajaEmpleado();
		}
	   
		return bajaEmpleado;
	}

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
	   
	   this.setTitle("Baja Empleado");

       jLabel1 = new javax.swing.JLabel();
       jFormattedTextField1 = new javax.swing.JFormattedTextField();
       jButton1 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jLabel1.setText("ID");

       jButton1.setText("Aceptar");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jLabel1)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                       .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jButton1)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
       
       pack();
   }// </editor-fold>

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	   ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.BAJA_EMPLEADO, Integer.valueOf(jFormattedTextField1.getText()).intValue());
   }

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new BajaEmpleado().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton jButton1;
   private javax.swing.JFormattedTextField jFormattedTextField1;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration

	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		if(id_evento_vista == EventoVista.BAJA_EMPLEADO_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha dado de baja el empleado con éxito", "Baja Empleado", JOptionPane.INFORMATION_MESSAGE);
		}
		else if(id_evento_vista == EventoVista.BAJA_EMPLEADO_FALLO){
			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el empleado que se desea dar de baja o tiene tareas pendientes", "Baja Empleado", JOptionPane.ERROR_MESSAGE);
		}
		
	}

}
