/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_empleados;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import selector_vista.EventoVista;
import tarea.Tarea;
import vista.Vista;
import controlador.ControladorAplicacionImp;
import controlador.EventoNegocio;
import empleado.*;

/**
 *
 * @author Ricardo
 */
public class MostrarEmpleado extends javax.swing.JFrame implements Vista {

	
	static private MostrarEmpleado mostrarEmpleado;
		

    public MostrarEmpleado() {
        initComponents();
    }
	static public MostrarEmpleado obtenerInstancia(){
		if(mostrarEmpleado == null){
			mostrarEmpleado = new MostrarEmpleado();
		}
		
		return mostrarEmpleado;
	}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	this.setTitle("Mostrar Empleado");

        jPanel1 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoSalario = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        labelDepartamento = new javax.swing.JLabel();
        campoDepartamento = new javax.swing.JTextField();
        labelDepartamento1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        radioTiempoParcial = new javax.swing.JRadioButton();
        radioTiempoCompleto = new javax.swing.JRadioButton();
        labelContraro = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        campoContrato = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelID.setText("ID");

        campoNombre.setEditable(false);

        campoSalario.setEditable(false);

        labelNombre.setText("Nombre");

        labelSalario.setText("Salario");

        labelDepartamento.setText("Departamento");

        campoDepartamento.setEditable(false);

        labelDepartamento1.setText("Tareas");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        labelDNI.setText("DNI");

        campoDNI.setEditable(false);

        radioTiempoParcial.setText("Tiempo Parcial");
        radioTiempoParcial.setToolTipText("");
        radioTiempoParcial.setEnabled(false);

        radioTiempoCompleto.setText("Tiempo Completo");
        radioTiempoCompleto.setEnabled(false);

        labelContraro.setText("Contrato");

        labelCorreo.setText("Correo");

        campoContrato.setEditable(false);

   
        
        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	campoIDActionPerformed(evt);
            }
        });
        
        campoCorreo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDepartamento1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSalario)
                                    .addComponent(labelDepartamento))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(campoDepartamento))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDNI)
                            .addComponent(labelNombre))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(campoDNI)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTiempoParcial)
                            .addComponent(radioTiempoCompleto))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContraro))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSalario))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDepartamento)
                            .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelNombre)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDNI))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraro)
                    .addComponent(campoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioTiempoCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreo)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioTiempoParcial))
                .addGap(18, 18, 18)
                .addComponent(labelDepartamento1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addWindowListener(new java.awt.event.WindowAdapter() { //cuando se cirre la pestaña borra lo anterior
            public void windowClosing(java.awt.event.WindowEvent evt) {
            	
            	
                 campoDNI.setText("");
                 campoDepartamento.setText("");
                campoID.setText("");
                 campoNombre.setText("");
                 campoSalario.setText("");
                 campoContrato.setText("");
                 campoCorreo.setText("");
                radioTiempoCompleto.setSelected(false);
               radioTiempoParcial.setSelected(false);
                 jTextArea1.setText(""); //borra lo anterior
     		
            }
        });
        
		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
		
        pack();
    }// </editor-fold>                        

    
    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {
        ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.MOSTRAR_EMPLEADO, Integer.valueOf(campoID.getText()).intValue());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarEmpleado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTextField campoContrato;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDepartamento;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelContraro;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelDepartamento1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JRadioButton radioTiempoCompleto;
    private javax.swing.JRadioButton radioTiempoParcial;
    // End of variables declaration                   

    @Override
	public void actualizar(int id_evento_vista, Object datos) {
        campoDNI.setText("");
        campoDepartamento.setText("");
     
        campoNombre.setText("");
        campoSalario.setText("");
        jTextArea1.setText(""); //borra lo anterior
		
		if(id_evento_vista == EventoVista.MOSTRAR_EMPLEADO_EXITO){
			
			
			
			if(datos.getClass().equals(EmpleadoTiempoCompleto.class))
			{
				EmpleadoTiempoCompleto empleado = (EmpleadoTiempoCompleto)datos;
				campoDNI.setText(empleado.getDni());
				campoDepartamento.setText(empleado.getDepartamento().getNombre());
				campoNombre.setText(empleado.getNombre_apellidos());
				campoSalario.setText(Double.toString(empleado.getSalario()));
				campoContrato.setText(empleado.getCodigoDeContrato());
				campoCorreo.setText("");
				radioTiempoCompleto.setSelected(true);
				radioTiempoParcial.setSelected(false);
				
				jTextArea1.append("ID\tNOMBRE \n\n");
				
				for(Tarea t: empleado.getLista_tareas()){
					jTextArea1.append(Integer.toString(t.getId()) + "\t" + t.getNombre()+ "\n"); 				
				}
			}
			else
			{
				EmpleadoTiempoParcial empleado = (EmpleadoTiempoParcial)datos;
				campoDNI.setText(empleado.getDni());
				campoDepartamento.setText(empleado.getDepartamento().getNombre());
				campoNombre.setText(empleado.getNombre_apellidos());
				campoSalario.setText(Double.toString(empleado.getSalario()));
				campoCorreo.setText(empleado.getCorreroElectronico());
				campoContrato.setText("");
				radioTiempoParcial.setSelected(true);
				radioTiempoCompleto.setSelected(false);
				
				jTextArea1.append("ID\tNOMBRE \n\n");
				
				for(Tarea t: empleado.getLista_tareas()){
					jTextArea1.append(Integer.toString(t.getId()) + "\t" + t.getNombre()+ "\n"); 
				}
			}
		

		}
		else if(id_evento_vista == EventoVista.MOSTRAR_EMPLEADO_FALLO){
			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el empleado que se desea mostrar", "Mostrar Empleado", JOptionPane.ERROR_MESSAGE);
		}
    }
	}