/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_empleados;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import selector_vista.EventoVista;
import vista.Vista;
import controlador.ControladorAplicacionImp;
import controlador.EventoNegocio;
import empleado.*;


/**
 *
 * @author Ricardo
 */
public class NuevoEmpleado extends javax.swing.JFrame implements Vista {

	
	static private NuevoEmpleado nuevoEmpleado;
	
    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado() {
        initComponents();
    }
    
    /**
     * Obtiene la instancia de la ventana
     * @return la instancia de la ventana
     */
    static public NuevoEmpleado obtenerInstancia(){
 	   if(nuevoEmpleado == null){
 		   nuevoEmpleado = new NuevoEmpleado();
 	   }
 	   
 	   return nuevoEmpleado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	this.setTitle("Nuevo Empleado");

        grupoDeRadioButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        labelSalario = new javax.swing.JLabel();
        labelNombreApellidos = new javax.swing.JLabel();
        campoNombreApellidos = new javax.swing.JTextField();
        campoDepartamento = new javax.swing.JTextField();
        labelDepartamento = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        botonRadioTiempoCompleto = new javax.swing.JRadioButton();
        botonRadioTiempoParcial = new javax.swing.JRadioButton();
        campoContrato = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        labelContrato = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();

        grupoDeRadioButton.add(botonRadioTiempoCompleto);
        grupoDeRadioButton.add(botonRadioTiempoParcial);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDNI.setText("DNI");

        labelSalario.setText("Salario");

        labelNombreApellidos.setText("Nombre y Apellidos");

        labelDepartamento.setText("Departamento");

        botonRadioTiempoCompleto.setText("Tiempo Completo");

        botonRadioTiempoParcial.setText("Tiempo Parcial");

        campoCorreo.setEditable(false);
        
        botonRadioTiempoCompleto.setSelected(true);

        botonAceptar.setText("Aceptar");

        labelContrato.setText("Contrato");

        labelCorreo.setText("Correo");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
         	   botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDNI)
                            .addComponent(labelNombreApellidos)
                            .addComponent(labelSalario)
                            .addComponent(labelDepartamento))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDepartamento)
                            .addComponent(campoDNI)
                            .addComponent(campoNombreApellidos)
                            .addComponent(campoSalario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonRadioTiempoCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(botonRadioTiempoParcial)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrato)
                            .addComponent(labelCorreo))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCorreo)
                            .addComponent(campoContrato))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDNI)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreApellidos)
                    .addComponent(campoNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartamento)
                    .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRadioTiempoParcial)
                    .addComponent(botonRadioTiempoCompleto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrato)
                    .addComponent(campoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreo)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonRadioTiempoCompleto.setSelected(true);
      
        botonRadioTiempoParcial.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent e) {
				campoCorreo.setEditable(true);
				campoContrato.setEditable(false);
				
			}        	
        });
        botonRadioTiempoCompleto.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent e) {
				campoContrato.setEditable(true);
				campoCorreo.setEditable(false);
			}        	
        });
        
		ImageIcon image = new ImageIcon("res/icono.png");

		this.setIconImage(image.getImage());
        
        pack();
    }// </editor-fold>                        

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {
 	   
    	
    	if(botonRadioTiempoCompleto.isSelected())
    	{
    		
    		EmpleadoTiempoCompleto  empleado = new EmpleadoTiempoCompleto(campoDNI.getText(),campoNombreApellidos.getText(),Double.valueOf(campoSalario.getText()).doubleValue(),campoDepartamento.getText(),campoContrato.getText());
    		  empleado.setActivo(true);
    	        ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.NUEVO_EMPLEADO, empleado);
    	}
    	else
    	{
    		
    		EmpleadoTiempoParcial empleado = new EmpleadoTiempoParcial(campoDNI.getText(),campoNombreApellidos.getText(),Double.valueOf(campoSalario.getText()).doubleValue(),campoDepartamento.getText(),campoCorreo.getText());
    		  empleado.setActivo(true);
    	        ControladorAplicacionImp.obtenerInstancia().accion(EventoNegocio.NUEVO_EMPLEADO, empleado);
    	}
 	  
 	
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEmpleado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAceptar;
    private javax.swing.JRadioButton botonRadioTiempoCompleto;
    private javax.swing.JRadioButton botonRadioTiempoParcial;
    private javax.swing.JTextField campoContrato;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDepartamento;
    private javax.swing.JTextField campoNombreApellidos;
    private javax.swing.JTextField campoSalario;
    private javax.swing.ButtonGroup grupoDeRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContrato;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelNombreApellidos;
    private javax.swing.JLabel labelSalario;
    // End of variables declaration                   
    @Override
	public void actualizar(int id_evento_vista, Object datos) {
	   if(id_evento_vista == EventoVista.NUEVO_EMPLEADO_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha creado el empleado con éxito con id " + (int)datos, "Creación Empleado", JOptionPane.INFORMATION_MESSAGE);
	   }
	   else if(id_evento_vista == EventoVista.NUEVO_EMPLEADO_DEPARTAMENTO_NO_EXISTE){
			JOptionPane.showMessageDialog(null, "ERROR!! El departamento no existe", "Creación Empleado", JOptionPane.ERROR_MESSAGE);
		}
	   else{
			JOptionPane.showMessageDialog(null, "ERROR!! El empleado no se ha creado", "Creación Empleado", JOptionPane.ERROR_MESSAGE);
	   }
	   
   }
}